# doc: https://pnpm.io/zh/settings#preferworkspacepackages
preferWorkspacePackages: true
# doc: https://pnpm.io/zh/settings#linkworkspacepackages
linkWorkspacePackages: deep
packages:
    - 'packages/core'
    - 'packages/ui'
    - 'packages/hooks'
    - 'packages/utils'
    - 'packages/pocket'
    - 'packages/animations'
    - 'packages/components/*'
    - 'apps/*'
